### ISSUE TITLE
Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by Cammoy** [talmobi/yt-search#15] opened 2020-07-15 11:02 UTC
TypeError: Cannot read property 'split' of undefined
    at node_modules/yt-search/dist/yt-search.min.js:1:4926

This used to work but all of a sudden it stops working.

**Comment by Cammoy** [comment] 2020-07-15 11:16
Ok, I copied the source, and it seems to work directly from that. The minified version does not work when getting a playlist only, so there is something strange going on in your build process I would think. Not sure what.

**Comment by talmobi** [comment] 2020-07-15 11:26
Halåj~

Have you tried version v2.1.2?

`npm install yt-search@latest`

**Comment by Cammoy** [comment] 2020-07-15 15:34
> Halåj~
> 
> Have you tried version v2.1.2?
> 
> `npm install yt-search@latest`

I did not check the latest, I was using 2.0.1, why no use axios?

**Comment by talmobi** [comment] 2020-07-15 16:28
The issue is related to a change in default behaviour by youtube's playlist page.

**Comment by Cammoy** [comment] 2020-07-15 16:52
> The issue is related to a change in default behaviour by youtube's playlist page.

Oh I see, I might chip in later and help to convert to TypeScript

**Comment by chaos87** [comment] 2020-07-16 01:07
Hi @talmobi,

I confirm the problem you fixed in v2.1.2 ( #13  ) is reappearing.

**Comment by talmobi** [comment] 2020-07-16 09:16
Yes it seems the playlist page on youtube is not served as pre-rendered HTML at all anymore even with polymer disabled. And therefore you cannot render the page with JS disabled.

example: https://www.youtube.com/playlist?list=PLwgpH_uE8MMXLkGoz7yZhy0dblUbEaqqV&disable_polymer=true

Working on a fix.

**Comment by talmobi** [comment] 2020-07-16 12:17
Halåj,

Published a new version 2.1.3 that uses a different user-agent for playlist pages that should return a pre-rendered html that is compatible with the current parsing logic.

YouTube seems to be undergoing some updates and may start returning these new pages for more user-agents soon which might break again soon.

Should work for now, though.

`npm install yt-search@latest`

**Comment by chaos87** [comment] 2020-07-16 14:49
Yeah it fixed it! Thanks

**Closed** 2020-07-21 13:38 UTC
