### ISSUE TITLE
video unavailable

### ISSUE THREAD

**Issue by PanSzelescik** [talmobi/yt-search#18] opened 2020-07-21 14:27 UTC
I often say that one day I can search for everything I want, and the next day I can find absolutely nothing because I have error: video unavailable. Unfortunately, I have no ideas what to do.

version: 2.1.3

**Comment by talmobi** [comment] 2020-07-21 14:59
Halåj,

Examples of search terms that work and don't work?

**Comment by oathompsonjones** [comment] 2020-07-21 15:16
I have the same issue. It was working fine until yesterday. 

Doing `await yts({ query: SEARCH_QUERY });` returrns the correct results, but doing `await yts({ videoId: VIDEO_ID });` throws an error saying only `video unavailable` (not a very helpful error).

As I said, this problem didn't occur until yesterday, and I have not changed my code.

**Comment by talmobi** [comment] 2020-07-21 15:31
YouTube has been going through some changes as of late. Will look into it.

**Comment by Cammoy** [comment] 2020-07-21 15:42
been having the same issue as well today.

**Comment by talmobi** [comment] 2020-07-21 18:54
Published a patch v2.1.4

`npm install yt-search@latest`

YouTube seems to have also stopped serving pre-rendered HTML for videos pages (as well as playlist pages). This new patch parses the data availalbe in the ytIinitalData json object instead of searching pre-rendered HTML.

Does this fix your issues?

**Comment by oathompsonjones** [comment] 2020-07-22 13:25
v2.1.4 does fix this issue, however, the `url` property of the object returned by doing `await yts({ videoId: VIDEO_ID });` is no longer returning the video ID, but instead returns either `https://youtube.com/user/USER_ID` or `https://youtube.com/channel/CHANNEL_ID`.

**Comment by talmobi** [comment] 2020-07-22 16:24
You're right tests for that didn't exist or had disappeared along the way.. Should be fixed now in v.2.1.5

**Comment by Cammoy** [comment] 2020-07-23 11:04
@talmobi in v2.1.5  I am now getting the following in the error response when I request a video
` {
"video": "could not find inital data in the html document",
"playlist": []
}`

**Comment by talmobi** [comment] 2020-07-23 15:50
Looks like the bot compatible pages have changed again. Published a fix for version v.2.1.6

**Comment by Cammoy** [comment] 2020-07-23 16:29
> Looks like the bot compatible pages have changed again. Published a fix for version v.2.1.6

Thanks!

**Comment by oathompsonjones** [comment] 2020-07-24 13:58
In v2.1.6, `await yts({ videoId: VIDEO_ID })` throws an error saying `could not find inital data in the html document`, looks to be a similar (if not the same) issue as the one above.

**Comment by talmobi** [comment] 2020-07-24 15:02
Hey,

I can't reproduce this on v.2.1.6, it seems to be working fine. Please try running `npm install yt-search@latest` again and see if it works. If not try deleting node_modules and try installing again.

**Comment by oathompsonjones** [comment] 2020-07-25 09:44
Hi, that was my mistake, I thought I had updated it to v.2.1.6, but apparently I hadn't. That's why I deleted my comment.

**Closed** 2020-07-25 13:32 UTC
